/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// DiscoveryResponseTypes : The response type that is associated with discovery request.
type DiscoveryResponseTypes string

// List of discoveryResponseTypes
const (
	VMWARE_DISCOVERY_DiscoveryResponseTypes DiscoveryResponseTypes = "vmwareDiscovery"
	RHV_DISCOVERY_DiscoveryResponseTypes    DiscoveryResponseTypes = "rhvDiscovery"
	CLOUD_DISCOVERY_DiscoveryResponseTypes  DiscoveryResponseTypes = "cloudDiscovery"
)
