/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetJobTryLogsResponseLinks struct {
	Self  *ManualBackupResponseLinksSelf `json:"self,omitempty"`
	Prev  *ManualBackupResponseLinksSelf `json:"prev,omitempty"`
	Next  *ManualBackupResponseLinksSelf `json:"next,omitempty"`
	First *ManualBackupResponseLinksSelf `json:"first,omitempty"`
	Last  *ManualBackupResponseLinksSelf `json:"last,omitempty"`
}
