/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Contains the discovery request data.
type AdmindiscoveryworkloadsworkloadTypestartData struct {
	// The resource type.
	Type_      string                                                  `json:"type"`
	Attributes *AdmindiscoveryworkloadsworkloadTypestartDataAttributes `json:"attributes"`
}
