/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetJobFileListResponseData struct {
	Type_      string                                `json:"type,omitempty"`
	Id         int32                                 `json:"id,omitempty"`
	Links      *GetJobFileListResponseDataLinks      `json:"links,omitempty"`
	Attributes *GetJobFileListResponseDataAttributes `json:"attributes,omitempty"`
}
