/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ManualBackupResponseLinks struct {
	Self      *ManualBackupResponseLinksSelf `json:"self,omitempty"`
	TryLogs   *ManualBackupResponseLinksSelf `json:"try-logs,omitempty"`
	FileLists *ManualBackupResponseLinksSelf `json:"file-lists,omitempty"`
}
