/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// DiscoveryStatus : The status of the discovery process.
type DiscoveryStatus string

// List of discoveryStatus
const (
	RUNNING_DiscoveryStatus DiscoveryStatus = "RUNNING"
	SUCCESS_DiscoveryStatus DiscoveryStatus = "SUCCESS"
	FAILED_DiscoveryStatus  DiscoveryStatus = "FAILED"
	UNKNOWN_DiscoveryStatus DiscoveryStatus = "UNKNOWN"
)
