/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ManualBackupResponseData struct {
	Type_      string                          `json:"type,omitempty"`
	Id         string                          `json:"id,omitempty"`
	Links      *ManualBackupResponseLinks      `json:"links,omitempty"`
	Attributes *ManualBackupResponseAttributes `json:"attributes,omitempty"`
}
