/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The discovery status response schema.
type InlineResponse2009 struct {
	Links *GetJobsResponseLinks     `json:"links,omitempty"`
	Data  []DiscoveryStatusPageData `json:"data"`
	Meta  *GetJobsResponseMeta      `json:"meta,omitempty"`
}
