/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetJobProgressLogsResponseMetaPagination struct {
	Prev   int32 `json:"prev,omitempty"`
	Next   int32 `json:"next,omitempty"`
	First  int32 `json:"first,omitempty"`
	Last   int32 `json:"last,omitempty"`
	Count  int32 `json:"count,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Limit  int32 `json:"limit,omitempty"`
}
