/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The request for the manual backup.
type AdminmanualbackupDataAttributes struct {
	// The name of the policy used to start the manual backup.
	PolicyName string `json:"policyName"`
	// The name of the schedule used to start the manual backup.
	ScheduleName string `json:"scheduleName,omitempty"`
	// The name of the client.
	ClientName string `json:"clientName,omitempty"`
	// A keyword that is added to the created image. Optional.
	Keyword string `json:"keyword,omitempty"`
	// The name of the Oracle or Microsoft SQL Server instance to back up.
	InstanceName string `json:"instanceName,omitempty"`
	// The name of the Microsoft SQL Server database to back up.
	DatabaseName string `json:"databaseName,omitempty"`
	// The Oracle RAC database name. The database name should be used along with the dbid.
	DbUniqueName string `json:"dbUniqueName,omitempty"`
	// The Oracle RAC database ID. The database ID should be used along with the dbUniqueName.
	Dbid string `json:"dbid,omitempty"`
}
