/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetJobTryLogsResponseAttributesTryLog struct {
	// The UTC timestamp of the log entry.
	Timestamp string `json:"timestamp,omitempty"`
	// The severity of the log message.
	Severity string `json:"severity,omitempty"`
	// The localized log message.
	Message string `json:"message"`
}
