/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse401 struct {
	// The NetBackup error code.
	ErrorCode int64 `json:"errorCode"`
	// The NetBackup error code description.
	ErrorMessage string `json:"errorMessage"`
	// Maps the attributes with the invalid values to an error that describes why the value is invalid, to provide more context to the nature of the error.
	AttributeErrors *interface{} `json:"attributeErrors,omitempty"`
	// A list that contains additional information about the error.
	ErrorDetails []string `json:"errorDetails,omitempty"`
	// If an API is supporting content-type multipart/form-data, then this holds a list of objects that contains names of failed files and associated error messages.
	FileUploadErrors []interface{} `json:"fileUploadErrors,omitempty"`
}
