/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The attributes specific to the workload.
type DiscoveryStatusPageAttributesAdditionalAttributes struct {
	// The NetBackup host used to perform the discovery. Applies to the following workloadTypes types: [VMware, RHV]
	DiscoveryHost string `json:"discoveryHost,omitempty"`
	// The frequency (in seconds) at which automatic discovery is performed. Applies to the following workloadTypes types: [VMware, RHV, CLOUD]
	DiscoveryFrequencySeconds int32 `json:"discoveryFrequencySeconds,omitempty"`
	// Indicates if automatic discovery is disabled. Applies to the following workloadTypes types: [VMware, RHV, CLOUD]
	IsDiscoveryDisabled bool `json:"isDiscoveryDisabled,omitempty"`
}
