/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// The try log entry for the type 'LOG'.
type JobPostRequestDataAttributesJobUpdateDataTryLogListData struct {
	// The UTC timestamp of when the try log entry was created.
	Timestamp time.Time `json:"timestamp"`
	// The severity of the log message.
	Severity string `json:"severity"`
	// The name of the process or program.
	Program string `json:"program"`
	// The process ID.
	Pid int32 `json:"pid"`
	// The log message.
	Message string `json:"message"`
}
