/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiscoveryResponseAttributes struct {
	// The name of the server for which the discovery request was submitted. Applies to the following response types: [vmwareDiscovery, rhvDiscovery, cloudDiscovery]
	ServerName string `json:"serverName,omitempty"`
	// The NetBackup host used to perform the discovery. Applies to the following response types: [vmwareDiscovery, rhvDiscovery]
	DiscoveryHost string `json:"discoveryHost,omitempty"`
}
