/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type DiscoveryStatusPageAttributes struct {
	// The name of the server.
	ServerName   string `json:"serverName"`
	WorkloadType string `json:"workloadType"`
	// The subtype as defined by the workload.
	WorkloadSubType string `json:"workloadSubType"`
	// The status of the discovery process.
	DiscoveryStatus string `json:"discoveryStatus"`
	// The UTC timestamp of when the last attempted discovery started.
	DiscoveryStartTime time.Time `json:"discoveryStartTime"`
	// The UTC timestamp of when the last attempted discovery finished.
	DiscoveryFinishTime time.Time `json:"discoveryFinishTime"`
	// The UTC timestamp of when the entry was updated.
	UpdateTime           time.Time                                          `json:"updateTime"`
	AdditionalAttributes *DiscoveryStatusPageAttributesAdditionalAttributes `json:"additionalAttributes,omitempty"`
}
