/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkloadName string

// List of workloadName
const (
	V_MWARE_WorkloadName WorkloadName = "VMware"
	RHV_WorkloadName     WorkloadName = "RHV"
	CLOUD_WorkloadName   WorkloadName = "CLOUD"
)
