/*
 * NetBackup Administration API
 *
 * The NetBackup Administration API provides access to administrative operations in NetBackup.
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JobPostRequestDataAttributesJobData struct {
	// The job type.
	JobType string `json:"jobType"`
	// The job subtype.
	JobSubType string `json:"jobSubType"`
	// The type of backup policy that is associated with the job.
	PolicyType string `json:"policyType,omitempty"`
	// The name of the group that initiated the job.
	JobGroup string `json:"jobGroup,omitempty"`
	// The job owner or the user that initiated the job.
	JobOwner string `json:"jobOwner,omitempty"`
	// The user name in the audit record.
	AuditUserName string `json:"auditUserName,omitempty"`
	// The domain name in the audit record.
	AuditDomainName string `json:"auditDomainName,omitempty"`
	// The domain type in the audit record.
	AuditDomainType int32 `json:"auditDomainType,omitempty"`
	// Indicates if the job can be restarted.
	Restartable bool `json:"restartable,omitempty"`
	// Indicates if the job can be stopped.
	Cancellable bool `json:"cancellable,omitempty"`
	// Indicates if the job can be resumed.
	Resumable bool `json:"resumable,omitempty"`
	// Indicates if the job can be suspended.
	Suspendable bool `json:"suspendable,omitempty"`
	// The host from which the job was initiated.
	ControlHost string `json:"controlHost,omitempty"`
	// The name of the source media server.
	SourceMediaServerName string `json:"sourceMediaServerName,omitempty"`
	// The name of the destination media server.
	DestinationMediaServerName string `json:"destinationMediaServerName,omitempty"`
}
