name: "docker: build release container"

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-default-release-container:
    runs-on: self-hosted

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.5.0
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            kmlebedev/netbackup-exporter
            ghcr.io/kmlebedev/netbackup-exporter
          tags: |
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=netbackup-exporter
            org.opencontainers.image.description=Netbackup admin job metrics exporter to prometheus
            org.opencontainers.image.vendor=Konstantin Lebedev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./docker
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
